[book]
authors = ["Christian Fosli"]
language = "en"
multilingual = false
src = "src"
title = "My notes"

[output.html]
git-repository-url = "https://github.com/christianfosli/notes"
edit-url-template = "https://github.com/christianfosli/notes/edit/main/{path}"
